services:
  postgres:
    image: postgres:15
    container_name: reachinbox_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: reachinbox
      POSTGRES_PASSWORD: reachinbox
      POSTGRES_DB: reachinbox_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: reachinbox_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
